Feat/group sessions
openmrs/openmrs-esm-fast-data-entry-app pull request #27
Opened 2022-08-30 14:56 UTC by ZacButko

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Adds in a mock for group session work flow including
- compact group search
- better session metadata fields
- "new group modal"

## Screenshots
https://user-images.githubusercontent.com/5445264/187470345-6de49568-3e92-4a94-9f83-41998451b0b7.mov

## Related Issue

## Other

2022-09-01 13:03 UTC, vasharma05 requested changes

2022-09-01 13:03 UTC, vasharma05 commented on src/group-form-entry-workflow/group-search/CompactGroupSearch.tsx
> +        onSubmit={() => undefined}
Can we also put the default value of the function in the `GroupSearchBar`

2022-09-01 14:38 UTC, ZacButko commented on src/context/GroupFormWorkflowContext.tsx
> +  const newPatientUuid = new URLSearchParams(search).get("patientUuid");
This actually isn't needed for the group session workflow. I'll remove it here and add it to fast data workflow

2022-09-01 14:47 UTC, ZacButko commented on src/context/GroupFormWorkflowContext.tsx
> +  const newPatientUuid = new URLSearchParams(search).get("patientUuid");
Can't verify the fix right now since I'm not able to create a patient at all on dev3 ✖️

2022-09-01 14:49 UTC, ZacButko commented on src/form-entry-workflow/patient-search-header/PatientSearchHeader.tsx
>            extensionSlotName="patient-search-bar-slot"
This is on line 38?

2022-09-01 15:14 UTC, ZacButko commented
Lots of good comments! Thanks for the thorough review Vineet. Changes are updated now.
Just to comment, most of the workflow is just mocked out for this PR. The group workflow is not fully working yet

2022-09-01 17:11 UTC, vasharma05 commented on src/context/GroupFormWorkflowContext.tsx
> +  const newPatientUuid = new URLSearchParams(search).get("patientUuid");
Ohh okay, no issues!

2022-09-01 17:13 UTC, vasharma05 commented on src/form-entry-workflow/patient-search-header/PatientSearchHeader.tsx
>            extensionSlotName="patient-search-bar-slot"
Ohh okay!
My bad, that section below this line was closed.

2022-09-01 17:13 UTC, vasharma05 commented on src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
> +        <Link to="../">
Ohh great!
Thanks!

2022-09-01 17:17 UTC, vasharma05 approved these changes

2022-09-02 08:53 UTC, merged

2022-09-02 17:43 UTC, ZacButko commented
Working mock coming soon (I needed a place for github to host this movie...)


https://user-images.githubusercontent.com/5445264/188208788-17e1ab39-5379-4866-873d-36dc857263f7.mov