(feat) Save and load distinct workflows per logged user
openmrs/openmrs-esm-fast-data-entry-app pull request #47
Opened 2023-01-16 12:36 UTC by icrc-psousa

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Workflow was being saved on browser localStorage independently of the logged user meaning that, if a user logged out and another user logged in using the same browser, the workflow from 1st user would be loaded and overwritten.
With this PR, the workflow is saved on localStorage having the userId as a suffix so that workflow is properly loaded/saved per user.

2023-01-16 12:56 UTC, icrc-psousa commented
Hi @denniskigen @gracepotma would it be possible to review and merge this PR?
Please assign the proper reviewers. Thanks!

2023-01-19 06:53 UTC, gracepotma commented
Following up on this now. Thanks for pinging me @icrc-psousa

2023-04-04 15:30 UTC, delphinepas commented
@ibacher could you please review this PR ? thank you cc @icrc-psousa @gracepotma @icrc-fdeniger

2023-04-04 16:16 UTC, ibacher requested changes
Largely this seems ok, but some changes should be made.

2023-04-04 16:16 UTC, ibacher commented on src/context/FormWorkflowReducer.ts
> +const persistData = (data, userId) => {
Why do we need to pass the `userId` as an argument here? Isn't it always stored in `data`?

2023-04-04 16:16 UTC, ibacher commented on src/context/FormWorkflowContext.tsx
> +          userId: user.username,
I would use the user's UUID rather than the username, especially as this is written to a store that's available outside of an application-authenticated context (this leaks usernames).

2023-05-03 10:05 UTC, pedroedrasousa commented on src/context/FormWorkflowReducer.ts
>  export const fdeWorkflowStorageVersion = "1.0.13";
Incremented to 1.1.13. Please confirm if incrementing the minor version is ok or if major should be incremented given that the local storage keys will be changed.

2023-05-03 10:06 UTC, pedroedrasousa commented on src/context/FormWorkflowReducer.ts
> +const persistData = (data, userId) => {
Right! No need, reviewed to only receive the data arg

2023-05-03 10:06 UTC, pedroedrasousa commented on src/context/FormWorkflowContext.tsx
> +          userId: user.username,
Reviewed to use the user UUID instead

2023-05-03 15:10 UTC, ibacher approved these changes

2023-05-04 13:04 UTC, merged