(feat) Group edit
openmrs/openmrs-esm-fast-data-entry-app pull request #49
Opened 2023-01-25 09:50 UTC by icrc-psousa

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Allow selected group to be edited and persisted when creating a new group session.

## Screenshots
![image](https://user-images.githubusercontent.com/68599335/214531572-a7d417f4-1480-4118-9214-59b700f064e8.png)
![image](https://user-images.githubusercontent.com/68599335/214531624-656bbddc-47a2-48d7-bca3-efd53edef8f0.png)

2023-04-17 22:34 UTC, ibacher requested changes
Thanks @icrc-psousa! Great work here. A few more nitpicky comments, but mostly looks very good.

2023-04-17 22:34 UTC, ibacher commented on src/add-group-modal/AddGroupModal.tsx
> +  const patientDetails = useGetPatient(patient.uuid);
Aren't these attributes available on the `patient` as passed in? I.e., as I see it, we're loading patients from the search extension, which should look like [this](https://github.com/openmrs/openmrs-esm-patient-management/blob/b623c77dc987f49099222028381a181dbd75d71c/packages/esm-patient-search-app/src/types/index.ts#L2). That would save us a request-per-patient, which is really quite substantial.

2023-04-17 22:34 UTC, ibacher commented on src/add-group-modal/AddGroupModal.tsx
> +        {patient?.display || identifier + " - " + givenName + " " + familyName}
Might be a good idea to have a check for undefined values here? Otherwise, the default is `undefined - undefined undefined`, which is a bit ugly.

2023-04-17 22:34 UTC, ibacher commented on src/add-group-modal/AddGroupModal.tsx
> +  const patientDetails = useGetPatient(patient.uuid);
If the problem is the patients passed in, just load them before rendering this component.

2023-04-17 22:34 UTC, ibacher commented on src/add-group-modal/AddGroupModal.tsx
> +const AddGroupModal = (props) => {
Types for `props` should still be declared and, in general, our code bases favour this syntax:

```js
({ patients, isCreate... }) =>
```

over:

```js
(props) => const { patients, isCreate... } = props;
```

(They are equivalent)

2023-04-17 22:34 UTC, ibacher commented on src/add-group-modal/AddGroupModal.tsx
> +  const [, setOpen] = useState(false);
This seems very bad. `isOpen` should be the default or else we should just get rid of this `useState()` altogether. Without maintaining the `open` variable, the calls to `setOpen()` are kind of superfluous.

 ```suggestion
  const [, setOpen] = useState(isOpen);
```

Alternatively, replace all the `setOpen(false)` calls with `handleCancel()`...

2023-04-17 22:34 UTC, ibacher commented on src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
> +  const [isOpen, setIsOpen] = useState(false);
```suggestion
  const [isOpen, setOpen] = useState(false);
```

2023-04-17 22:34 UTC, ibacher commented on src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
> +          onClick={() => setIsOpen(true)}
It would probably be best to wrap this in a `useCallback()`

2023-04-17 22:34 UTC, ibacher commented on src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
> +  };
Since these are passed as props to child elements, they should definitely use `useCallback()`. `useCallback()` memoises the function so the variable always refers to a stable function. Without this, on each render, `handleCancel` (for example) will point to a different function. This means that each render of this component will cause the child components (especially the `AddGroupModal`) to completely re-render.

2023-04-17 22:34 UTC, ibacher commented on src/group-form-entry-workflow/attendance-table/AttendanceTable.tsx
> +  });
1. This should probably be wrapped in `useMemo()` for the same reasons as above.
2. This would be a decent point to actually load the patient records for this group (though it would be better to just try to extract the attributes [here](https://github.com/openmrs/openmrs-esm-fast-data-entry-app/blob/4d3d44babc35b22e358f0880197ccbcf461ec678/src/context/GroupFormWorkflowReducer.ts#L92)

2023-06-05 16:16 UTC, icrc-psousa commented on src/group-form-entry-workflow/attendance-table/AttendanceTable.tsx
> +  });
Wrapped in `useMemo()` as suggested

2023-06-05 16:17 UTC, icrc-psousa commented on src/group-form-entry-workflow/group-search-header/GroupSearchHeader.tsx
> +  };
Reviewed functions to use `useCallback()`

2023-06-12 19:47 UTC, merged