(feat) Add Support for Pre-Filled Questions
openmrs/openmrs-esm-fast-data-entry-app pull request #70
Opened 2024-01-19 18:44 UTC by icrc-jofrancisco

## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

## Related Issue

## Other

2024-01-22 13:18 UTC, ibacher requested changes
Thanks @icrc-jofrancisco, but I do think we want to try to collect things as a standard form element instead of adding yet another form schema in the configuration.

2024-01-22 13:18 UTC, ibacher commented on src/config-schema.ts
> +      answers: {
Why is this element necessary?

2024-01-22 13:18 UTC, ibacher commented on src/FormBootstrap.tsx
> +  const { activeSessionMeta } = useContext(GroupFormWorkflowContext);
I would move this up in the compontn a big.

2024-01-22 13:18 UTC, ibacher commented on src/FormBootstrap.tsx
> +};
```suggestion
};

```

2024-01-22 13:18 UTC, ibacher commented on src/group-form-entry-workflow/SessionDetailsForm.tsx
> +  const questions = useMemo(
What is this doing?

2024-01-22 13:18 UTC, ibacher commented on src/group-form-entry-workflow/SessionDetailsForm.tsx
> +          {getSpecificQuestionsByForm(specificQuestions, formUuid).length >
Why are we calling `getSpecificQuestionsByForm()` twice here instead of relying on a single call?

2024-01-22 13:18 UTC, ibacher commented on src/group-form-entry-workflow/SessionDetailsForm.tsx
> +            0 && (
Always prefer:

```jsx
condition ? <ReactJSX> : null
```

2024-01-22 13:18 UTC, ibacher commented on src/config-schema.ts
> +      answers: {
Basically, can we rework things to use the existing form?

2024-01-22 14:11 UTC, icrc-jofrancisco commented
> Thanks @icrc-jofrancisco, but I do think we want to try to collect things as a standard form element instead of adding yet another form schema in the configuration.

Thanks @ibacher !
I understand your point, the idea is that these are just a few questions. 
The reason I did it this way is because the logic for fetching the schema and rendering the labels and the form is only in the next phase, here we only have the `formuuid`. In other words, with the other approach, the request to fetch the schema is called twice. 
So, what do you think would be the best approach?

2024-01-22 14:12 UTC, icrc-jofrancisco commented on src/config-schema.ts
> +      answers: {
Thanks @ibacher , This element is just to know the translated label of the question, coming from the backend, thus avoiding specifying a hardcoded label.

2024-01-22 14:13 UTC, icrc-jofrancisco commented on src/group-form-entry-workflow/SessionDetailsForm.tsx
> +  const questions = useMemo(
To search for the form for which we are using in and see if there are any specific questions for this session/form.

2024-01-23 16:22 UTC, icrc-jofrancisco commented
> > Thanks @icrc-jofrancisco, but I do think we want to try to collect things as a standard form element instead of adding yet another form schema in the configuration.
> 
> Thanks @ibacher ! I understand your point, the idea is that these are just a few questions. The reason I did it this way is because the logic for fetching the schema and rendering the labels and the form is only in the next phase, here we only have the `formuuid`. In other words, with the other approach, the request to fetch the schema is called twice. So, what do you think would be the best approach?

Hi @ibacher , Actually, I've implemented your suggestion. Now, all you need to do is specify the questionId and the forms list. It'll automatically fetch the labels and values for the questions and answers. 
Super simple configuration, right?

If you've got more suggestions,feel free to comment, Appreciate your input!

2024-02-01 19:37 UTC, ibacher approved these changes

2024-02-01 19:37 UTC, merged