O3-2413: (test) Setup playwright for automated tests in Fast Data Entry App
openmrs/openmrs-esm-fast-data-entry-app pull request #88
Opened 2024-12-22 17:04 UTC by dilankavishka

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR is for setting up the fast data entry app for end-to-end testing.

## Screenshots

## Related Issue

https://openmrs.atlassian.net/browse/O3-2413

## Other

2024-12-22 17:05 UTC, dilankavishka commented
@jayasanka-sack , @NethmiRodrigo Can you review this please?

2024-12-29 10:05 UTC, jayasanka-sack requested changes
Found this in the failed build:
```
➤ YN0028: The lockfile would have been modified by this install, which is explicitly forbidden.
```
Run `yarn install` locally and push changes to avoid the error message

2024-12-29 10:09 UTC, jayasanka-sack requested changes
Thanks for the PR @dilankavishka ! I've left some comments, have a look when you are free. Also you need to update the jest config file as well, check this PR: https://github.com/openmrs/openmrs-esm-stock-management/pull/231

2024-12-29 10:09 UTC, jayasanka-sack commented on e2e/README.md
> +# E2E Tests
Delete this file

2024-12-29 10:09 UTC, jayasanka-sack commented on .github/workflows/e2e.yml
> +          overwrite: true
Add a new line at the end of the file.

2024-12-29 10:09 UTC, jayasanka-sack commented on tests-examples/demo-todo-app.spec.ts
> +import { test, expect, type Page } from '@playwright/test';
What is this file for? Seems like an unnecessary one.

2024-12-29 18:54 UTC, dilankavishka commented
@jayasanka-sack made the changes and need to write a small test for this.

2024-12-30 12:01 UTC, jayasanka-sack reviewed
Great! Include a very basic test for this PR and that would be enough. Ex the fast data entry app loads properly (just check only the title)

2024-12-30 12:01 UTC, jayasanka-sack commented on jest.config.json
> +  "setupFilesAfterEnv": ["<rootDir>/src/setup-tests.ts"],
Include changes that are only relevant to E2E tests.

2024-12-31 06:41 UTC, dilankavishka commented
@jayasanka-sack , while i'm trying to write an example test i have some challenges:

1. 
<img width="1680" alt="Screenshot 2024-12-31 at 12 07 55" src="https://github.com/user-attachments/assets/90b38f3d-9036-492d-8fab-a1becedd3530" />

after give yarn test-e2e --headed it's shows an error like this.

2. here is the page.ts

<img width="1680" alt="Screenshot 2024-12-31 at 12 08 11" src="https://github.com/user-attachments/assets/924c9b72-6aec-45bb-a61a-e9aaebaf8b42" />

3. here is the specs.ts

<img width="1680" alt="Screenshot 2024-12-31 at 12 08 15" src="https://github.com/user-attachments/assets/8f565606-38a2-4b2e-ac38-bb1c151cdec3" />

2024-12-31 07:22 UTC, jayasanka-sack reviewed
@dilankavishka Seems like you are not running the server or haven't copied the environment variables file (or both). Check this doc:
https://openmrs.atlassian.net/wiki/spaces/docs/pages/150962731/Testing+Frontend+Modules+O3#Running-tests

2024-12-31 07:24 UTC, jayasanka-sack reviewed
Also, add this section to the main readme file:

Line 104 to 111
https://github.com/openmrs/openmrs-esm-patient-chart/blob/a928b899060d6f347539c1491ed73e80de718e4f/README.md?plain=1#L104


The new link to the e2e links should be: https://openmrs.atlassian.net/wiki/spaces/docs/pages/150962731/Testing+Frontend+Modules+O3

2025-01-28 06:58 UTC, dilankavishka commented
@jayasanka-sack Could you please review this again. I think i need a bit help with writing the sample test for this.

2025-01-29 12:12 UTC, jayasanka-sack approved these changes
Thanks for getting this done, @dilankavishka!

2025-01-29 12:12 UTC, merged